name: forest_guard
description: The mobile app client for the Forest Guard AI Model built and deployed by Team LISA for the AI4Good Hackathon.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.14.1+3
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  firebase_auth: ^0.18.1+2
  firebase_messaging: ^7.0.3
  geolocator: ^6.1.1
  google_maps_flutter: ^1.0.3
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
